### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by yjiawqgj** [agent-squirrel/nfty-arr-script#1]
I want to use radarr to download movies, import, hard link, rename, and then execute tinymediamanager to grab movie data, how to write a script?  I don't understand code at all.  Just saw that you wrote it well, but I won't edit it either.  Can you help me write one?  I wrote one myself, choose to trigger on import!  And passed the test in radarr,                                   #!/bin/bash

 /volume1/tms/tinyMediaManager movie -u -n        can be executed correctly in the terminal but it cannot be triggered automatically. You can see variables in the wiki notification on the official website.  But I don't know how to use it?

**Comment by agent-squirrel** [comment]
I'm not sure this repo is what you want, this script is simply to fire a notification to ntfy.sh when a film/tv show is imported.

**Comment by yjiawqgj** [comment]
Not what I want. I need RADARR to execute the TMM program to download the movie data after completing the movie hard link and renaming the movie name. I can't code, I can only copy, I just need this function, but this is a huge gap for my level. Can you help me?

**Comment by agent-squirrel** [comment]
Unfortunately this repo is only for the code I have written. You might be better off asking on the Radarr subreddit or Discord servers.

**Comment by yjiawqgj** [comment]
They do not support scripting issues. I'm about to give up.

**Comment by agent-squirrel** [comment]
Have you asked here? https://www.reddit.com/r/radarr/

**Comment by yjiawqgj** [comment]
Yes I asked in Discord and reddit and they replied that this is not supported. I searched in github with arr as the keyword, and found your script, but it didn't work for me.
